# Generated by Django 3.1.7 on 2021-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3_theme', '0002_auto_20210225_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='confrence',
            name='image',
            field=models.ImageField(default='', upload_to='admin-lte/images'),
        ),
    ]
